export const PLAYERS_LIST = [
  {
    teamName: "IND",
    teamId: "2",
    players: [
      {
        id: "1413",
        name: "Virat Kohli",
        imageId: 244980,
        role: "Batsman",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm medium",
      },
      {
        id: "576",
        name: "Rohit Sharma",
        imageId: 244982,
        role: "Batsman",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "1446",
        name: "Shikhar Dhawan",
        imageId: 170660,
        role: "Batsman",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "11808",
        name: "Shubman Gill",
        imageId: 171042,
        role: "Batsman",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "9428",
        name: "Shreyas Iyer",
        imageId: 171024,
        role: "Batsman",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm legbreak",
      },
      {
        id: "1836",
        name: "Manish Pandey",
        imageId: 171022,
        role: "Batsman",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm medium",
      },
      {
        id: "2195",
        name: "Mayank Agarwal",
        imageId: 171091,
        role: "Batsman",
        battingStyle: "Right-hand bat",
      },
      {
        id: "12094",
        name: "Prithvi Shaw",
        imageId: 171030,
        role: "Batsman",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "1448",
        name: "Cheteshwar Pujara",
        imageId: 153263,
        role: "Batsman",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm legbreak",
      },
      {
        id: "1447",
        name: "Ajinkya Rahane",
        imageId: 171082,
        role: "Batsman",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm medium",
      },
      {
        id: "9647",
        name: "Hardik Pandya",
        imageId: 244973,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "8424",
        name: "Hanuma Vihari",
        imageId: 171080,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "587",
        name: "Ravindra Jadeja",
        imageId: 170670,
        role: "All-rounder",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Left-arm orthodox",
      },
      {
        id: "1593",
        name: "Ravichandran Ashwin",
        imageId: 244976,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },

      {
        id: "8733",
        name: "KL Rahul",
        imageId: 244975,
        role: "Wicket Keeper",
        battingStyle: "Right-hand bat",
      },
      {
        id: "8271",
        name: "Sanju Samson",
        imageId: 226289,
        role: "Wicket Keeper",
        battingStyle: "Right-hand bat",
      },
      {
        id: "1465",
        name: "Wriddhiman Saha",
        imageId: 171058,
        role: "Wicket Keeper",
        battingStyle: "Right-hand bat",
      },
      {
        id: "10744",
        name: "Rishabh Pant",
        imageId: 244978,
        role: "Wicket Keeper",
        battingStyle: "Left-hand bat",
      },
      {
        id: "7909",
        name: "Mohammed Shami",
        imageId: 244977,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "9311",
        name: "Jasprit Bumrah",
        imageId: 170685,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast",
      },
      {
        id: "8292",
        name: "Kuldeep Yadav",
        imageId: 170683,
        role: "Bowler",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Left-arm chinaman",
      },
      {
        id: "7910",
        name: "Yuzvendra Chahal",
        imageId: 244981,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm legbreak",
      },
      {
        id: "9715",
        name: "Navdeep Saini",
        imageId: 226400,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast",
      },
      {
        id: "8683",
        name: "Shardul Thakur",
        imageId: 226224,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "1858",
        name: "Umesh Yadav",
        imageId: 153874,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast",
      },
      {
        id: "10808",
        name: "Mohammed Siraj",
        imageId: 171039,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
    ],
  },
  {
    teamName: "AFG",
    teamid: "96",
    players: [
      {
        id: "3004",
        name: "Asghar Afghan",
        imageId: 170835,
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
        role: "Batsman",
      },
      {
        id: "8277",
        name: "Hashmatullah Shahidi",
        imageId: 170837,
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm offbreak",
        role: "Batsman",
      },
      {
        id: "12068",
        name: "Hazratullah Zazai",
        imageId: 244750,
        battingStyle: "Left-hand bat",
        bowlingStyle: "Left-arm orthodox",
        role: "Batsman",
      },
      {
        id: "8375",
        name: "Najibullah Zadran",
        imageId: 244758,
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm offbreak",
        role: "Batsman",
      },
      {
        id: "3010",
        name: "Noor Ali Zadran",
        imageId: 170831,
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
        role: "Batsman",
      },
      {
        id: "8571",
        name: "Rahmat Shah",
        imageId: 244767,
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm legbreak",
        role: "All-rounder",
      },
      {
        id: "3011",
        name: "Samiullah Shinwari",
        imageId: 170849,
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm legbreak",
        role: "All-rounder",
      },
      {
        id: "8030",
        name: "Gulbadin Naib",
        imageId: 244748,
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm medium",
        role: "All-rounder",
      },
      {
        id: "3007",
        name: "Mohammad Nabi",
        imageId: 244755,
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
        role: "All-rounder",
      },
      {
        id: "10738",
        name: "Rashid Khan",
        imageId: 244769,
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm legbreak",
        role: "All-rounder",
      },
      {
        id: "3014",
        name: "Mohammad Shahzad",
        imageId: 170855,
        battingStyle: "Right-hand bat",
        role: "Wicket Keeper",
      },
      {
        id: "6476",
        name: "Aftab Alam",
        imageId: 170861,
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
        role: "Bowler",
      },
      {
        id: "8029",
        name: "Dawlat Zadran",
        imageId: 170859,
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
        role: "Bowler",
      },
      {
        id: "3001",
        name: "Hamid Hassan",
        imageId: 170863,
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast",
        role: "Bowler",
      },
      {
        id: "12071",
        name: "Mujeeb Ur Rahman",
        imageId: 244756,
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
        role: "Bowler",
      },
    ],
  },
  {
    teamName: "IRE",
    teamId: "27",
    players: [
      {
        id: "625",
        name: "William Porterfield",
        imageId: 171103,
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm offbreak",
        role: "Batsman",
      },
      {
        id: "13942",
        name: "James McCollum",
        imageId: 174146,
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm medium",
        role: "Batsman",
      },
      {
        id: "6710",
        name: "Andrew Balbirnie",
        imageId: 244616,
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
        role: "Batsman",
      },
      {
        id: "10415",
        name: "Tyrone Kane",
        imageId: 171110,
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
        role: "All-rounder",
      },
      {
        id: "690",
        name: "Kevin O Brien",
        imageId: 171113,
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
        role: "All-rounder",
      },
      {
        id: "1114",
        name: "Paul Stirling",
        imageId: 244652,
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
        role: "All-rounder",
      },
      {
        id: "7985",
        name: "Stuart Thompson",
        imageId: 153763,
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm fast-medium",
        role: "All-rounder",
      },
      {
        id: "739",
        name: "Gary Wilson",
        imageId: 171118,
        battingStyle: "Right-hand bat",
        role: "Wicket Keeper",
      },
      {
        id: "11131",
        name: "Lorcan Tucker",
        imageId: 244650,
        battingStyle: "Right-hand bat",
        role: "Wicket Keeper",
      },
      {
        id: "10099",
        name: "Peter Chase",
        imageId: 153778,
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
        role: "Bowler",
      },
      {
        id: "6329",
        name: "George Dockrell",
        imageId: 244638,
        battingStyle: "Right-hand bat",
        bowlingStyle: "Left-arm orthodox",
        role: "Bowler",
      },
      {
        id: "6661",
        name: "Tim Murtagh",
        imageId: 171129,
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm fast-medium",
        role: "Bowler",
      },
      {
        id: "10449",
        name: "Mark Adair",
        imageId: 244651,
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast",
        role: "Bowler",
      },
      {
        id: "9667",
        name: "Andy McBrine",
        imageId: 171124,
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm offbreak",
        role: "Bowler",
      },
      {
        id: "10451",
        name: "Barry McCarthy",
        imageId: 244623,
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm medium",
        role: "Bowler",
      },
      {
        id: "626",
        name: "Boyd Rankin",
        imageId: 171134,
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm fast-medium",
        role: "Bowler",
      },
    ],
  },
  {
    teamName: "PAK",
    teamId: "3",
    players: [
      {
        id: "10863",
        name: "Fakhar Zaman",
        imageId: 244937,
        battingStyle: "Left-hand bat",
        bowlingStyle: "Left-arm orthodox",
        role: "Batsman",
      },
      {
        id: "8364",
        name: "Imam-ul-Haq",
        imageId: 170765,
        role: "Batsman",
        battingStyle: "Left-hand bat",
      },
      {
        id: "8359",
        name: "Babar Azam",
        imageId: 244936,
        role: "Batsman",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "9565",
        name: "Asif Ali",
        imageId: 244935,
        role: "Batsman",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm medium",
      },
      {
        id: "8299",
        name: "Haris Sohail",
        imageId: 170777,
        role: "All-rounder",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Left-arm orthodox",
      },
      {
        id: "360",
        name: "Mohammad Hafeez",
        imageId: 170776,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "33",
        name: "Shoaib Malik",
        imageId: 170775,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "11186",
        name: "Shadab Khan",
        imageId: 244959,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm legbreak",
      },
      {
        id: "10408",
        name: "Imad Wasim",
        imageId: 170782,
        role: "All-rounder",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Left-arm orthodox",
      },

      {
        id: "881",
        name: "Sarfaraz Ahmed",
        imageId: 170787,
        role: "Wicket Keeper",
        battingStyle: "Right-hand bat",
      },

      {
        id: "1051",
        name: "Wahab Riaz",
        imageId: 170809,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Left-arm fast",
      },
      {
        id: "12160",
        name: "Shaheen Afridi",
        imageId: 244960,
        role: "Bowler",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Left-arm fast-medium",
      },
      {
        id: "11320",
        name: "Hasan Ali",
        imageId: 170804,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "14248",
        name: "Mohammad Hasnain",
        imageId: 244952,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "1917",
        name: "Mohammad Amir",
        imageId: 170813,
        role: "Bowler",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Left-arm fast-medium",
      },
    ],
  },
  {
    teamId: "4",
    teamName: "AUS",
    players: [
      {
        id: "1643",
        name: "Aaron Finch",
        imageId: 244784,
        role: "Batsman",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Left-arm orthodox",
      },
      {
        id: "2250",
        name: "Steven Smith",
        imageId: 244808,
        role: "Batsman",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm legbreak",
      },
      {
        id: "1739",
        name: "David Warner",
        imageId: 244788,
        role: "Batsman",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm legbreak",
      },
      {
        id: "8121",
        name: "Joe Burns",
        imageId: 180293,
        role: "Batsman",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm medium",
      },
      {
        id: "12228",
        name: "Will Pucovski",
        imageId: 165716,
        role: "Batsman",
        battingStyle: "Right-hand bat",
      },
      {
        id: "8497",
        name: "Travis Head",
        imageId: 147703,
        role: "Batsman",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },

      {
        id: "7662",
        name: "Glenn Maxwell",
        imageId: 244786,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "8989",
        name: "Marcus Stoinis",
        imageId: 244801,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm medium",
      },
      {
        id: "1437",
        name: "Moises Henriques",
        imageId: 152405,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "10182",
        name: "Marnus Labuschagne",
        imageId: 184115,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm legbreak",
      },
      {
        id: "8130",
        name: "Michael Neser",
        imageId: 155994,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "8508",
        name: "Ashton Agar",
        imageId: 244781,
        role: "All-rounder",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Left-arm orthodox",
      },
      {
        id: "12225",
        name: "Cameron Green",
        imageId: 198706,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm medium",
      },
      {
        id: "13162",
        name: "Daniel Sams",
        imageId: 180315,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Left-arm fast-medium",
      },
      {
        id: "8136",
        name: "Sean Abbott",
        imageId: 191413,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm medium",
      },
      {
        id: "9200",
        name: "Alex Carey",
        imageId: 170667,
        role: "Wicket Keeper",
        battingStyle: "Left-hand bat",
      },
      {
        id: "1649",
        name: "Matthew Wade",
        imageId: 244799,
        role: "Wicket Keeper",
        battingStyle: "Left-hand bat",
      },
      {
        id: "1994",
        name: "Tim Paine",
        imageId: 155979,
        role: "Wicket Keeper",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm medium",
      },
      {
        id: "8095",
        name: "Pat Cummins",
        imageId: 244803,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast",
      },
      {
        id: "7850",
        name: "Nathan Lyon",
        imageId: 170650,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "7710",
        name: "Mitchell Starc",
        imageId: 244806,
        role: "Bowler",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Left-arm fast",
      },
      {
        id: "8642",
        name: "Adam Zampa",
        imageId: 244782,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm legbreak",
      },
      {
        id: "6258",
        name: "Josh Hazlewood",
        imageId: 244790,
        role: "Bowler",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "9617",
        name: "Andrew Tye",
        imageId: 156051,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "2283",
        name: "James Pattinson",
        imageId: 151576,
        role: "Bowler",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm fast",
      },
      {
        id: "10626",
        name: "Mitchell Swepson",
        imageId: 156052,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm legbreak",
      },
    ],
  },
  {
    teamId: "5",
    teamName: "SL",
    players: [
      {
        id: "6243",
        name: "Lahiru Thirimanne",
        imageId: 170704,
        role: "Batsman",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm medium",
      },
      {
        id: "7952",
        name: "Dimuth Karunaratne",
        imageId: 170700,
        role: "Batsman",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm medium",
      },
      {
        id: "10939",
        name: "Avishka Fernando",
        imageId: 170702,
        role: "Batsman",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "1629",
        name: "Angelo Mathews",
        imageId: 170706,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "7872",
        name: "Dhananjaya de Silva",
        imageId: 244845,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "7891",
        name: "Milinda Siriwardana",
        imageId: 170712,
        role: "All-rounder",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Left-arm orthodox",
      },
      {
        id: "2281",
        name: "Thisara Perera",
        imageId: 170714,
        role: "All-rounder",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "1920",
        name: "Isuru Udana",
        imageId: 170710,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Left-arm fast-medium",
      },
      {
        id: "6470",
        name: "Jeevan Mendis",
        imageId: 170716,
        role: "All-rounder",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm legbreak",
      },
      {
        id: "8116",
        name: "Kusal Perera",
        imageId: 170718,
        role: "Wicket Keeper",
        battingStyle: "Left-hand bat",
      },
      {
        id: "9494",
        name: "Kusal Mendis",
        imageId: 244672,
        role: "Wicket Keeper",
        battingStyle: "Right-hand bat",
      },

      {
        id: "1785",
        name: "Suranga Lakmal",
        imageId: 170726,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm medium",
      },
      {
        id: "111",
        name: "Lasith Malinga",
        imageId: 170724,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast",
      },
      {
        id: "10469",
        name: "Jeffrey Vandersay",
        imageId: 244667,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm legbreak",
      },
      {
        id: "6730",
        name: "Nuwan Pradeep",
        imageId: 170728,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
    ],
  },
  {
    teamId: "6",
    teamName: "BAN",
    players: [
      {
        id: "612",
        name: "Tamim Iqbal",
        imageId: 170899,
        role: "Batsman",
        battingStyle: "Left-hand bat",
      },
      {
        id: "8233",
        name: "Soumya Sarkar",
        imageId: 244930,
        role: "Batsman",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm medium",
      },
      {
        id: "8231",
        name: "Sabbir Rahman",
        imageId: 170903,
        role: "Batsman",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm legbreak",
      },
      {
        id: "1121",
        name: "Mahmudullah",
        imageId: 170905,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "544",
        name: "Shakib Al Hasan",
        imageId: 244928,
        role: "All-rounder",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Left-arm orthodox",
      },
      {
        id: "8541",
        name: "Mosaddek Hossain",
        imageId: 244923,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "11084",
        name: "Mohammad Saifuddin",
        imageId: 170907,
        role: "All-rounder",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "11081",
        name: "Mehidy Hasan Miraz",
        imageId: 244919,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },

      {
        id: "394",
        name: "Mushfiqur Rahim",
        imageId: 170916,
        role: "Wicket Keeper",
        battingStyle: "Right-hand bat",
      },
      {
        id: "8540",
        name: "Litton Das",
        imageId: 244922,
        role: "Wicket Keeper",
        battingStyle: "Right-hand bat",
      },
      {
        id: "8221",
        name: "Mohammad Mithun",
        imageId: 170918,
        role: "Wicket Keeper",
        battingStyle: "Right-hand bat",
      },

      {
        id: "323",
        name: "Mashrafe Mortaza",
        imageId: 170920,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "1736",
        name: "Rubel Hossain",
        imageId: 170922,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "9863",
        name: "Mustafizur Rahman",
        imageId: 244924,
        role: "Bowler",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Left-arm fast-medium",
      },
      {
        id: "8536",
        name: "Abu Jayed",
        imageId: 170927,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
    ],
  },
  {
    teamId: "9",
    teamName: "ENG",
    players: [
      {
        id: "624",
        name: "Eoin Morgan",
        imageId: 170936,
        role: "Batsman",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm medium",
      },
      {
        id: "8019",
        name: "Joe Root",
        imageId: 170942,
        role: "Batsman",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "6534",
        name: "Jason Roy",
        imageId: 170941,
        role: "Batsman",
        battingStyle: "Right-hand bat",
      },
      {
        id: "10045",
        name: "Liam Livingstone",
        imageId: 244797,
        role: "Batsman",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm legbreak",
      },
      {
        id: "6660",
        name: "Dawid Malan",
        imageId: 244793,
        role: "Batsman",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm legbreak",
      },
      {
        id: "6692",
        name: "Moeen Ali",
        imageId: 244796,
        role: "All-rounder",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "6557",
        name: "Ben Stokes",
        imageId: 244791,
        role: "All-rounder",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "6670",
        name: "Chris Woakes",
        imageId: 244787,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "9522",
        name: "Tom Curran",
        imageId: 170967,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "7854",
        name: "Lewis Gregory",
        imageId: 180929,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "10420",
        name: "Sam Curran",
        imageId: 244812,
        role: "All-rounder",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Left-arm fast-medium",
      },

      {
        id: "6507",
        name: "Jonny Bairstow",
        imageId: 170976,
        role: "Wicket Keeper",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm medium",
      },
      {
        id: "2258",
        name: "Jos Buttler",
        imageId: 244800,
        role: "Wicket Keeper",
        battingStyle: "Right-hand bat",
      },
      {
        id: "7990",
        name: "Sam Billings",
        imageId: 156173,
        role: "Wicket Keeper",
        battingStyle: "Right-hand bat",
      },
      {
        id: "1742",
        name: "Adil Rashid",
        imageId: 244789,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm legbreak",
      },
      {
        id: "8383",
        name: "Mark Wood",
        imageId: 244802,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast",
      },
      {
        id: "11540",
        name: "Jofra Archer",
        imageId: 170970,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast",
      },
      {
        id: "8022",
        name: "Olly Stone",
        imageId: 156823,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast",
      },
      {
        id: "8349",
        name: "Reece Topley",
        imageId: 244807,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Left-arm fast-medium",
      },
      {
        id: "6532",
        name: "Chris Jordan",
        imageId: 244783,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
    ],
  },
  {
    teamId: "10",
    teamName: "WI",
    players: [
      {
        id: "1610",
        name: "Darren Bravo",
        imageId: 170790,
        role: "Batsman",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "247",
        name: "Chris Gayle",
        imageId: 170801,
        role: "Batsman",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "8579",
        name: "Evin Lewis",
        imageId: 244670,
        role: "Batsman",
        battingStyle: "Left-hand bat",
      },
      {
        id: "9789",
        name: "Shimron Hetmyer",
        imageId: 171232,
        role: "Batsman",
        battingStyle: "Left-hand bat",
      },
      {
        id: "9785",
        name: "Fabian Allen",
        imageId: 170794,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Left-arm orthodox",
      },
      {
        id: "8313",
        name: "Jason Holder",
        imageId: 244677,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "7736",
        name: "Andre Russell",
        imageId: 170821,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast",
      },
      {
        id: "8110",
        name: "Carlos Brathwaite",
        imageId: 170798,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },

      {
        id: "10384",
        name: "Shai Hope",
        imageId: 170814,
        role: "Wicket Keeper",
        battingStyle: "Right-hand bat",
      },
      {
        id: "9406",
        name: "Nicholas Pooran",
        imageId: 244722,
        role: "Wicket Keeper",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "9395",
        name: "Sheldon Cottrell",
        imageId: 244835,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Left-arm fast-medium",
      },
      {
        id: "8092",
        name: "Shannon Gabriel",
        imageId: 170826,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "1359",
        name: "Kemar Roach",
        imageId: 170820,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast",
      },
      {
        id: "7922",
        name: "Ashley Nurse",
        imageId: 170817,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "11442",
        name: "Oshane Thomas",
        imageId: 170824,
        role: "Bowler",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm fast",
      },
    ],
  },
  {
    teamId: "11",
    teamName: "RSA",
    players: [
      {
        id: "7825",
        name: "Faf du Plessis",
        imageId: 170639,
        role: "Batsman",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm legbreak",
      },
      {
        id: "6349",
        name: "David Miller",
        imageId: 244759,
        role: "Batsman",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "9582",
        name: "Aiden Markram",
        imageId: 244757,
        role: "Batsman",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "9554",
        name: "Rassie van der Dussen",
        imageId: 170691,
        role: "Batsman",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm legbreak",
      },

      {
        id: "211",
        name: "Jean-Paul Duminy",
        imageId: 170693,
        role: "All-rounder",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "9601",
        name: "Andile Phehlukwayo",
        imageId: 244749,
        role: "All-rounder",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm medium",
      },
      {
        id: "8651",
        name: "Dwaine Pretorius",
        imageId: 170695,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "8333",
        name: "Chris Morris",
        imageId: 170696,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },

      {
        id: "8520",
        name: "Quinton de Kock",
        imageId: 244766,
        role: "Wicket Keeper",
        battingStyle: "Left-hand bat",
      },
      {
        id: "6667",
        name: "Imran Tahir",
        imageId: 170764,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm legbreak",
      },
      {
        id: "9585",
        name: "Kagiso Rabada",
        imageId: 244765,
        role: "Bowler",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm fast",
      },
      {
        id: "9603",
        name: "Lungi Ngidi",
        imageId: 244772,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast",
      },
      {
        id: "10173",
        name: "Tabraiz Shamsi",
        imageId: 244777,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Left-arm chinaman",
      },
      {
        id: "9490",
        name: "Beuran Hendricks",
        imageId: 157349,
        role: "Bowler",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Left-arm fast-medium",
      },
    ],
  },
  {
    teamId: "12",
    teamName: "ZIM",
    players: [
      {
        id: "6334",
        name: "Craig Ervine",
        imageId: 244697,
        role: "Batsman",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "425",
        name: "Hamilton Masakadza",
        imageId: 148340,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm medium",
      },
      {
        id: "9354",
        name: "Sikandar Raza",
        imageId: 244709,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "441",
        name: "Sean Williams",
        imageId: 244708,
        role: "All-rounder",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Left-arm orthodox",
      },
      {
        id: "9737",
        name: "Solomon Mire",
        imageId: 148344,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "10168",
        name: "Brian Chari",
        imageId: 174146,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "782",
        name: "Timycen Maruma",
        imageId: 153323,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm legbreak",
      },
      {
        id: "170",
        name: "Elton Chigumbura",
        imageId: 148346,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm medium",
      },

      {
        id: "781",
        name: "Regis Chakabva",
        imageId: 244700,
        role: "Wicket Keeper",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "180",
        name: "Brendan Taylor",
        imageId: 155186,
        role: "Wicket Keeper",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "10195",
        name: "Peter Moor",
        imageId: 148350,
        role: "Wicket Keeper",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "6483",
        name: "Tendai Chatara",
        imageId: 244710,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "10066",
        name: "Donald Tiripano",
        imageId: 153440,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "428",
        name: "Chris Mpofu",
        imageId: 148328,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm medium",
      },
      {
        id: "2289",
        name: "Kyle Jarvis",
        imageId: 148326,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast",
      },
      {
        id: "11224",
        name: "Brandon Mavuta",
        imageId: 174146,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm legbreak",
      },
    ],
  },
  {
    teamId: "13",
    teamName: "NZ",
    players: [
      {
        id: "1457",
        name: "Martin Guptill",
        imageId: 244827,
        role: "Batsman",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "521",
        name: "Ross Taylor",
        imageId: 170729,
        role: "Batsman",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "6326",
        name: "Kane Williamson",
        imageId: 244826,
        role: "Batsman",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "10694",
        name: "Henry Nicholls",
        imageId: 170745,
        role: "Batsman",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },

      {
        id: "8983",
        name: "James Neesham",
        imageId: 244821,
        role: "All-rounder",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm medium",
      },
      {
        id: "8081",
        name: "Colin de Grandhomme",
        imageId: 170735,
        role: "All-rounder",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "8085",
        name: "Colin Munro",
        imageId: 170737,
        role: "All-rounder",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm medium",
      },
      {
        id: "10100",
        name: "Mitchell Santner",
        imageId: 244828,
        role: "All-rounder",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Left-arm orthodox",
      },

      {
        id: "8216",
        name: "Tom Latham",
        imageId: 170743,
        role: "Wicket Keeper",
        battingStyle: "Left-hand bat",
        bowlingStyle: "Right-arm medium",
      },
      {
        id: "10717",
        name: "Tom Blundell",
        imageId: 170757,
        role: "Wicket Keeper",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm offbreak",
      },
      {
        id: "8117",
        name: "Trent Boult",
        imageId: 244829,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Left-arm fast-medium",
      },
      {
        id: "9067",
        name: "Matt Henry",
        imageId: 170751,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "1057",
        name: "Tim Southee",
        imageId: 244824,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast-medium",
      },
      {
        id: "8561",
        name: "Ish Sodhi",
        imageId: 244819,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm legbreak",
      },
      {
        id: "10692",
        name: "Lockie Ferguson",
        imageId: 244820,
        role: "Bowler",
        battingStyle: "Right-hand bat",
        bowlingStyle: "Right-arm fast",
      },
    ],
  },
];
