export const PLAYERS_ACTION_TYPE = {
  FATCH_PLAYERS_DATA_SUCCESS: "players/FATCH_PLAYERS_DATA_SUCCESS",
  FATCH_PLAYERS_DATA_FAILED: "players/FATCH_PLAYERS_DATA_FAILED",
  FATCH_PLAYER_DATA_SUCCESS: "players/FATCH_PLAYER_DATA_SUCCESS",
  FATCH_PLAYER_DATA_FAILED: "players/FATCH_PLAYER_DATA_FAILED",
};
